name: Предложить улучшение
description: Опишите задачу пользователя и желаемый результат
title: "[Идея]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: change
    attributes:
      label: Что хочется изменить?
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Какую проблему это решает?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Как сейчас приходится обходить проблему?
